name: Build

on: [ workflow_dispatch ]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
          gradle-version: current

      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: iRE67WIn
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: build/libs/!(*-@(javadoc|sources)).jar
          version-type: release
          version: 2.0.5
          loaders: neoforge
          game-versions: 1.21
          java: 21
          name: ""
          changelog-file: changelog-1.21.*
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
